---

NAME: aachen
NAME_: aachen
NAME_CAP: Aachen
NAME_UPCASE: AACHEN

TITLE: Aachen
SUBTITLE: Elements of Carolingian Fantasy

tohtml: lowdown -Thtml --html-no-skiphtml --html-no-escapehtml ${in} -o - >> ${out}
topdf: wkhtmltopdf --disable-smart-shrinking ${in} ${out}

